### PR TITLE
Public destructor should be virtual - C.35.

### PR DESCRIPTION
**Pull request by mpb27**
Making the destructor `virtual` would allow us to extend Frame and place what ever data we need in it.  It is also best practice according to the CppCoreGuidelines C.35, and was done for the `AnalyzerResults` class.

The work being done on `FrameV2` is similar in that it is intended to allow analyzers to place arbitrary data into `FrameV2`.

### CODE REVIEW

**Comment by mpb27** [comment]
@huffman @Marcus10110

**Comment by huffman** [comment]
Hi @mpb27!

Thank you for taking the time to put up a PR. Because `Frame` is not virtual, this would unfortunately break compatibility with existing analyzers.

Ideally we'd like to add future improvements to `FrameV2`. Do you have any thoughts on improvements we could add there? Any example use-cases would be helpful!

**Comment by mpb27** [comment]
Hi @huffman,

Indeed that would break the ABI - not sure how I missed that `Frame` isn't virtual.

How about making `FrameV2` virtual, then extending it into a `ByteArrayFrame` as an example for others to create customized frames?   That way more complex frames such as `EthernetFrame` could be implemented by the analyzer DLL.

I'm working on a [NMEA-0183 analyzer](/mpb27/nmea0183-analyzer/) that needs string storage.  At the moment, I'm giving `Frame` ownership of a class that contains the string by placing a raw pointer into `mData1` [(link)](https://github.com/mpb27/nmea0183-analyzer/blob/2192f47765663cd3c1a1360fa41eb6966696ea60/src/NmeaAnalyzer.cpp#L207).  Then I free the raw pointers in `AnalyzerResults`'s destructor by iterating over all the `Frame`s that it contains [(link)](https://github.com/mpb27/nmea0183-analyzer/blob/2192f47765663cd3c1a1360fa41eb6966696ea60/src/NmeaAnalyzerResults.cpp#L16).  This doesn't guarantee that it can't leak memory, but I think you are using `SetupResults()` to clear the previous results [(link)](https://github.com/mpb27/nmea0183-analyzer/blob/2192f47765663cd3c1a1360fa41eb6966696ea60/src/NmeaAnalyzer.cpp#L33) which will call `~AnalyzerResults()`.

**Comment by mpb27** [comment]
Closing b/c `virtual` would break ABI.

**Comment by huffman** [comment]
Hi @mpb27,

For the string case, is the current FrameV2 storage sufficient? For instance, you can store arbitrary values inside of it, including strings. FrameV2 is not fully compatible with the Frame (V1) API, though, in that the analyzer doesn't have access to the FrameV2 object (and the values added) for rendering strings that show up in the UI. The FrameV2 objects are visible in the data table, and accessible to downstream HLAs, though.

We also need to be able to serialize/deserialize the data for storing to disk and converting between the C++ and Python representations. I can imagine ways we could do that with user-defined types, but I think it would make the API more complex, and give us less control over how the data is represented, unfortunately.

All that said, I'm curious if the string storage in FrameV2 is sufficient for your use-case, or whether there are other cases that wouldn't be satisfied.

**Pull request closed without merging**
